[package]
name = "regex-fuzz"
version = "0.0.0"
authors = [
  "The Rust Project Developers",
  "David Korczynski <david@adalogics.com>",
  "Addison Crump <me@addisoncrump.info>",
  "Andrew Gallant <jamslam@gmail.com>",
]
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1.3.0", features = ["derive"] }
libfuzzer-sys = { version = "0.4.1", features = ["arbitrary-derive"] }
regex = { path = "..", features = ["logging"] }
regex-automata = { path = "../regex-automata", features = ["logging"] }
regex-syntax = { version = "0.8", features = ["arbitrary"] }
regex-lite = { path = "../regex-lite", version = "0.1.8" }
fancy-regex = "0.16.2"
egg = "0.7"
rand = "0.9"
rand_regex = "0.18.1"
onig = "6.4.0" 
pcre2 = "0.2.3"  
once_cell = "1.21.3"
ptree = "0.5.2"


[dependencies.env_logger]
version = "0.9.3"
default-features = false
features = ["atty", "humantime", "termcolor"]

[lib]
path = "src/lib.rs"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_diff_eqs"
path = "fuzz_targets/fuzz_diff_eqs.rs"

[[bin]]
name="testOne"
path="fuzz_targets/testOne.rs"

[profile.release]
opt-level = 3
debug = true

[profile.dev]
opt-level = 3
debug = true

[profile.test]
opt-level = 3
debug = true
